plugins:
  - prettier
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  sourceType: module
  ecmaVersion: 2022
env:
  es6: true
  node: true
  browser: true
globals:
  foundry: readonly
  game: readonly
  ui: readonly
  canvas: readonly
  CONFIG: readonly
  CONST: readonly
  Actor: readonly
  ActorSheet: readonly
  Item: readonly
  ItemSheet: readonly
  ChatMessage: readonly
  Roll: readonly
  Dialog: readonly
  Hooks: readonly
  Actors: readonly
  Items: readonly
  Handlebars: readonly
  TextEditor: readonly
  FormApplication: readonly
  DocumentSheet: readonly
  Combat: readonly
  Combatant: readonly
  renderTemplate: readonly
  getTemplate: readonly
  loadTemplates: readonly
rules:
  prettier/prettier: error